// Import du type Metadata de Next.js pour typer nos métadonnées
import type { Metadata } from "next";

// Import des polices Google via l’API Next.js Font
import { Geist, Geist_Mono } from "next/font/google";

// Chargement du CSS global (Tailwind + éventuelles autres règles)
import "./globals.css";

// Import de la Navbar — notre composant de navigation commun à toutes les pages
import Navbar from "@/components/Navbar";

// Définition des variables de polices pour Geist Sans et Geist Mono
const geistSans = Geist({
	variable: "--font-geist-sans", // nom de la variable CSS
	subsets: ["latin"], // jeu de caractères chargé
});
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// Métadonnées globales du site (titre, description, SEO)
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// 🔗 Composant racine qui englobe toutes les pages de ton app
export default function RootLayout({
	children, // Prop spéciale contenant le contenu de chaque page
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			{" "}
			{/* Déclaration de la langue de l’app */}
			<body
				// Application des polices via les variables CSS + antialiasing typographique
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* Barre de navigation partagée par toutes les pages */}
				<Navbar />

				{/* Contenu spécifique à chaque route (app/page.tsx, app/projets/page.tsx, etc.) */}
				{children}
			</body>
		</html>
	);
}
