// Import du type Metadata de Next.js pour typer nos métadonnées
import type { Metadata } from "next";


// Chargement du CSS global (Tailwind + éventuelles autres règles)
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Poppins } from "next/font/google";

const poppins = Poppins({
	weight:["400", "600", "700"],
	subsets: ["latin"],
	display: "swap",
})


// Métadonnées globales du site (titre, description, SEO)
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// 🔗 Composant racine qui englobe toutes les pages de ton app
export default function RootLayout({
	children, // Prop spéciale contenant le contenu de chaque page
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			{""}
			{/* Déclaration de la langue de l’app */}
			<body className={poppins.className}>
				{/* Barre de navigation partagée par toutes les pages */}
				<Navbar />
				{/* Contenu spécifique à chaque route (app/page.tsx, app/projets/page.tsx, etc.) */}
				{children}
			</body>
		</html>
	);
}
